// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3RoKSTowkEF0K6Ec_sMAsQjw2Mk2fiNo',
    appId: '1:648401860186:web:8792a564d870486886ca63',
    messagingSenderId: '648401860186',
    projectId: 'chatapp-40fe3',
    authDomain: 'chatapp-40fe3.firebaseapp.com',
    storageBucket: 'chatapp-40fe3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZo7Wp304fRro10wCyUgKX41cFoL9Nv5w',
    appId: '1:648401860186:android:87b219cc849c175886ca63',
    messagingSenderId: '648401860186',
    projectId: 'chatapp-40fe3',
    storageBucket: 'chatapp-40fe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPqS8-7x_3tIiELFxJGA5V6bFYnoddNqs',
    appId: '1:648401860186:ios:e9e6f59b7f39f8c886ca63',
    messagingSenderId: '648401860186',
    projectId: 'chatapp-40fe3',
    storageBucket: 'chatapp-40fe3.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPqS8-7x_3tIiELFxJGA5V6bFYnoddNqs',
    appId: '1:648401860186:ios:32a27f192a08011186ca63',
    messagingSenderId: '648401860186',
    projectId: 'chatapp-40fe3',
    storageBucket: 'chatapp-40fe3.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
